version: "3.7"
services:
  app:
    build: ./app/
    working_dir: /work
    volumes:
      - .:/work:cached
      - /work/app/__pycache__
      - /work/app/.venv/
      - /work/app/.tox/
      - /work/app/.mypy_cache
      - /work/app/.pytest_cache
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
