name: Tox

on: pull_request

jobs:
  lint:
    name: Tox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose build

      - name: Tox
        run: docker-compose run --rm app /bin/bash -c "cd app/ && tox"